{
  "grouping" : "TIT1",
  "album" : "TALB",
  "albumartist": "TPE2",
  "comment" : "COMM",
  "artist": "TPE1",
  "comment": "COMM",
  "composer": "TCOM",
  "discnumber": "TPOS",
  "disctotal":"TPOS",
  "genre":"TCON",
  "picture":"APIC"
  "title": "TIT2",
  "tracknumber":"TRCK",
  "tracktotal":"TRCK",
  "year":"TDRC"
}
